name: 'action-scraps'
description: 'create scrap data'

inputs:
  github_token:
    description: 'GitHub Token for creating tag & branch'
    required: true
  issue_number:
    description: 'target issue number'
    required: true


outputs:
  result:
    description: 'result json'

runs:
  using: 'node20'
  main: 'dist/index.js'
