url: https://www.yslibrary.net
permalink: /:year/:month/:day/:title/

# THEME-SPECIFIC CONFIGURATION
title: CodingFeline
description: Thoughts, stories and ideas
avatar: assets/img/logo.png
favicon: assets/favicon.ico

# Header and footer text
header_text: <p>Thoughts, stories and ideas</p>
header_feature_image: assets/img/dactyl.jpeg
footer_text: © 2020, yshrsmz

# Blog
excerpt: true
post_navigation: true
color_image: /assets/img/lineart.png

# Features
katex: true
mermeid: false
google_analytics: UA-61198465-1
cookie_consent: false
color_theme: auto

comments:
  disqus_shortname: yslibrary

# PAGINATION
paginate: 10
paginate_path: "/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  toc_levels: 1..3
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

include: [.well-known]
