# SITE CONFIGURATION
baseurl: ""
url: https://www.codingfeline.com
permalink: /:year/:month/:day/:title/

# THEME-SPECIFIC CONFIGURATION
title: CodingFeline
description: Thoughts, stories and ideas
avatar: assets/img/logo.png
favicon: assets/favicon.ico

# Header and footer text
header_text: <p>Thoughts, stories and ideas</p>
header_feature_image: assets/img/dactyl.jpeg
header_feature_image_responsive: true
footer_text: © 2020, yshrsmz

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true
mermeid: false
google_analytics: UA-61198465-1
google_analytics_ga4: G-XZRK8ZP8XC
cookie_consent: false
color_theme: auto

# Comments
comments:
  disqus_shortname: yslibrary
  # cusdis_app_id:                                        # Your cusdis data-app-id
  # utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
  #   repo:                                               # your public comments repository (e.g. owner/repo)
  #   issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 10
paginate_path: "/page:num"

# PORTFOLIO
# collections:
#   portfolio:
#     output: true
#     permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
kramdown:
  toc_levels: 1..3
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - "Gemfile"
  - "Gemfile.lock"
  - "type-on-strap.gemspec"
  - "*.gem"
  - ".idea"
  - "vendor/*"
  - "LICENSE"
  - "README.md"
  - "screenshot.png"
  - "assets/package.json"
  - "assets/node_modules"
  - "assets/gulpfile.js"
  - "assets/Dockerfile"

include: [.well-known]
