name: dispatch scrap update

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'Issue number'
        type: number
        required: true
      github_token:
        description: 'github token'
        type: string
        required: true

jobs:
  create-scrap:
    runs-on: ubuntu-latest
    steps:
      - name: create scrap
        uses: ./packages/action-create-scrap
        with:
          issue_number: ${{ github.event.inputs.issue_number }}
          github_token: ${{ github.event.inputs.github_token }}
