name: Build and deploy site to GitHub Pages

on:
  push:
    branches:
      - development

concurrency:
  group: deploy-gh-pages
  cancel-in-progress: true

jobs:
  gh-pages:
    # skip deployment if `[skip]` is in the commit message
    if: ${{ !contains(github.event.head_commit.message, '[skip]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

      - name: Check Node.js version
        run: |
          mise exec node -- node --version

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm blog:build

      - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/blog/.vitepress/dist
          publish_branch: master
          force_orphan: true
