name: fetch and save recent contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,4'

concurrency:
  group: fetch-and-save-recent-contributions
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.COMMIT_TOKEN }}

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Check Node.js version
        run: |
          mise exec node -- node --version

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile

      - name: fetch recent contributions
        run: pnpm --filter @codingfeline/recent-contributions start
        env:
          GH_PUBLIC_PAT: ${{ secrets.GH_PUBLIC_PAT }}

      - name: commit if there are new contributions
        run: |
          git config --global user.email "recent-contributions-bot@usersusers.noreply.github.com"
          git config --global user.name "recent-contributions-bot"
          git add ./packages/blog/data/recent-contributions.json
          git commit -m "chore: update recent contributions"
          git push origin development
