name: fetch and save recent contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,4'

concurrency:
  group: fetch-and-save-recent-contributions
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.COMMIT_TOKEN }}

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4

      - name: Check Node.js version
        run: |
          mise exec node -- node --version

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile

      - name: fetch recent contributions
        run: pnpm --filter @codingfeline/recent-contributions start
        env:
          GH_PUBLIC_PAT: ${{ secrets.GH_PUBLIC_PAT }}

      - name: commit if there are new contributions
        run: |
          git config --global user.email "recent-contributions-bot@usersusers.noreply.github.com"
          git config --global user.name "recent-contributions-bot"
          git add ./packages/blog/data/recent-contributions.json
          git commit -m "chore: update recent contributions"
          git push origin development
